### ISSUE TITLE
Failing in notebook

### ISSUE THREAD

**Issue by grburgess** [tqdm/tqdm#1359]
- [x] I have marked all applicable categories:
    + [ ] exception-raising bug
    + [x] visual output bug
- [x] I have visited the [source website], and in particular
  read the [known issues]
- [x] I have searched through the [issue tracker] for duplicates
- [x] I have mentioned version numbers, operating system and
  environment, where applicable:
 ```
4.64.0 3.10.6 (main, Aug 11 2022, 13:36:31) [Clang 13.1.6 (clang-1316.0.21.2.5)] darwin
 ```

Upon switching to an Apple M1 chip, I have been unable to get the progress bars to work in the notebook.
It is possible I have not installed something correctly.

JupyterLab configuration:

```
JupyterLab v3.4.5
Other labextensions (built into JupyterLab)
   app dir: /opt/homebrew/Cellar/python@3.10/3.10.6_1/Frameworks/Python.framework/Versions/3.10/share/jupyter/lab
        @aquirdturtle/collapsible_headings v3.0.0 enabled OK
        @jlab-enhanced/cell-toolbar v3.5.1 enabled OK
        @jupyter-widgets/jupyterlab-manager v5.0.2 enabled OK
        @timkpaine/jupyterlab_miami_nights v0.3.1 enabled OK
        @yudai-nkt/jupyterlab_city-lights-theme v3.0.0 enabled OK
        js v0.1.0 enabled OK
        jupyter-matplotlib v0.11.2 enabled OK
        jupyterlab-code-snippets v2.1.0 enabled OK
        jupyterlab-jupytext v1.3.8 enabled OK
        jupyterlab-theme-hale v0.1.3 enabled OK

```

While everything works fine in the shell, when I run something in the notebookI get this:

```python
from tqdm.notebook import tqdm

for i in tqdm(range(10)):
    
    pass
```

```
root:
    n: 0
    total: 10
    elapsed: 0.021565914154052734
    ncols: null
    nrows: 84
    prefix: ""
    ascii: false
    unit: "it"
    unit_scale: false
    rate: null
    bar_format: null
    postfix: null
    unit_divisor: 1000
    initial: 0
    colour: null
```

[source website]: https://github.com/tqdm/tqdm/
[known issues]: https://github.com/tqdm/tqdm/#faq-and-known-issues
[issue tracker]: https://github.com/tqdm/tqdm/issues?q=
